version: "3.8"

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lahrasab.ramzan36@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: always

  app:
    build: .
    environment:
      - PORT=8080
      - API_KEY=AIzaSyCVRkuYt2KzjhirpnzJn10_UQLIIqWUnc
      - GOOGLE_CLIENT_ID=619777684899-mc8fs7guet9hjifathlaeb5c7nfcsi0h.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - ENVIRONMENT=production
      - SESSION_SECRET_KEY=jxzRt3+1e5BxP7OXLhqTk5CmnrQgZq6sH7OxyQZ2Hd4c
      - OAUTH_REDIRECT_URL=https://go-rammarly.duckdns.org/auth/google/callback
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`go-rammarly.duckdns.org`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    restart: always
    depends_on:
      - traefik
    # To achieve high availability on a single node,
    # you can scale this service with: docker-compose up --scale app=3 -d

  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - "3001:3001"
    restart: always
