// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Activity struct {
	ID        int64
	UserID    int64
	Type      string
	Content   string
	CreatedAt sql.NullTime
}

type User struct {
	ID        int64
	GoogleID  string
	Email     string
	Name      string
	Picture   sql.NullString
	CreatedAt sql.NullTime
}
