// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO activities (user_id, type, sender, content)
VALUES (?, ?, ?, ?)
`

type CreateActivityParams struct {
	UserID  int64
	Type    string
	Sender  string
	Content string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.ExecContext(ctx, createActivity,
		arg.UserID,
		arg.Type,
		arg.Sender,
		arg.Content,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, email, name, picture)
VALUES (?, ?, ?, ?)
RETURNING id, google_id, email, name, picture, created_at
`

type CreateUserParams struct {
	GoogleID string
	Email    string
	Name     string
	Picture  sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.Picture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, name, picture, created_at
FROM users
WHERE google_id = ?
LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.CreatedAt,
	)
	return i, err
}
